import json
import os

CONFIG_FILE = 'config/settings.json'
GENERATED_DIR = 'generated'

def load_config():
    if not os.path.exists(CONFIG_FILE):
        return {}
    try:
        with open(CONFIG_FILE, 'r') as f:
            return json.load(f)
    except:
        return {}

def save_config(config):
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=4)
    
    # Auto-generate system configs on save
    generate_netplan_config(config)
    generate_dhcp_config(config)
    generate_pppoe_config(config)
    generate_loadbalance_script(config)

def generate_netplan_config(config):
    """
    Generates a Netplan YAML configuration based on the stored settings.
    """
    network = config.get('network', {})
    netplan = {
        'network': {
            'version': 2,
            'renderer': 'networkd',
            'ethernets': {}
        }
    }

    for iface, settings in network.items():
        role = settings.get('role')
        ip = settings.get('ip')
        
        if role == 'wan':
            # WAN usually gets IP via DHCP from ISP or static
            # For simplicity, assuming DHCP if no IP provided
            if ip:
                netplan['network']['ethernets'][iface] = {
                    'addresses': [ip] if '/' in ip else [f"{ip}/24"],
                    'dhcp4': False
                }
            else:
                netplan['network']['ethernets'][iface] = {
                    'dhcp4': True
                }
        elif role == 'lan':
            if ip:
                netplan['network']['ethernets'][iface] = {
                    'addresses': [ip] if '/' in ip else [f"{ip}/24"],
                    'dhcp4': False
                }
    
    # Write to file
    with open(os.path.join(GENERATED_DIR, '01-netcfg.yaml'), 'w') as f:
        # Simple YAML dump (avoiding pyyaml dependency for this demo)
        f.write("# This file is generated by Ubuntu Router UI\n")
        f.write(json.dumps(netplan, indent=2)) # Using JSON as valid YAML subset for simplicity

def generate_dhcp_config(config):
    """
    Generates ISC DHCP Server config
    """
    dhcp_settings = config.get('dhcp', {})
    content = "default-lease-time 600;\nmax-lease-time 7200;\nauthoritative;\n\n"
    
    for iface, settings in dhcp_settings.items():
        if settings.get('enabled'):
            start = settings.get('start')
            end = settings.get('end')
            # Simplified subnet calculation (assuming /24)
            if start:
                subnet = start.rsplit('.', 1)[0] + '.0'
                content += f"subnet {subnet} netmask 255.255.255.0 {{\n"
                content += f"  range {start} {end};\n"
                content += f"  option routers {subnet.rsplit('.', 1)[0] + '.1'};\n" # Guessing router IP
                content += f"  option domain-name-servers 8.8.8.8, 8.8.4.4;\n"
                content += f"}}\n\n"

    with open(os.path.join(GENERATED_DIR, 'dhcpd.conf'), 'w') as f:
        f.write(content)

def generate_pppoe_config(config):
    """
    Generates PPPoE Server config (rp-pppoe)
    """
    pppoe_settings = config.get('pppoe', {})
    content = "# PPPoE Server Configuration\n"
    
    for iface, settings in pppoe_settings.items():
        if settings.get('enabled'):
            local_ip = settings.get('local_ip')
            remote_start = settings.get('remote_start')
            content += f"# Interface: {iface}\n"
            content += f"require-chap\n"
            content += f"lcp-echo-interval 10\n"
            content += f"lcp-echo-failure 2\n"
            content += f"ms-dns {settings.get('dns')}\n"
            # Note: Real PPPoE config is more complex and involves multiple files (pap-secrets, pppoe-server-options)
    
    with open(os.path.join(GENERATED_DIR, 'pppoe-server-options'), 'w') as f:
        f.write(content)

def generate_loadbalance_script(config):
    """
    Generates a shell script to configure routing for load balancing
    """
    lb_settings = config.get('loadbalance', {})
    content = "#!/bin/bash\n# Load Balancing Setup\n\n"
    content += "ip rule flush\nip route flush cache\n\n"
    
    # This is a very simplified example of policy routing
    for iface, settings in lb_settings.items():
        if settings.get('enabled'):
            weight = settings.get('weight')
            content += f"# Interface {iface} weight {weight}\n"
            # In reality:
            # 1. Create routing tables
            # 2. Add default routes to tables
            # 3. Add ip rules
            # 4. Add nexthop weights to default route
            
    with open(os.path.join(GENERATED_DIR, 'setup_loadbalance.sh'), 'w') as f:
        f.write(content)
